# Generated by Django 5.2.1 on 2025-05-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
                ("slug", models.SlugField(unique=True, verbose_name="スラッグ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.category",
                        verbose_name="親カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        max_length=500, null=True, verbose_name="タイトル"
                    ),
                ),
                ("url", models.URLField(null=True, unique=True, verbose_name="URL")),
                (
                    "post_date",
                    models.DateField(blank=True, null=True, verbose_name="投稿日"),
                ),
                (
                    "updated_date",
                    models.DateField(blank=True, null=True, verbose_name="更新日"),
                ),
                (
                    "content_intro",
                    models.TextField(blank=True, null=True, verbose_name="導入文"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="タグ"
                    ),
                ),
                (
                    "headings",
                    models.TextField(blank=True, null=True, verbose_name="見出し"),
                ),
                (
                    "book_title",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="書籍タイトル",
                    ),
                ),
                (
                    "book_author",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="著者"
                    ),
                ),
                (
                    "book_isbn",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "book_asin",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="ASIN"
                    ),
                ),
                ("word_count", models.IntegerField(default=0, verbose_name="文字数")),
                (
                    "internal_links",
                    models.TextField(blank=True, null=True, verbose_name="内部リンク"),
                ),
                (
                    "frequent_words",
                    models.TextField(blank=True, null=True, verbose_name="頻出語"),
                ),
                (
                    "broken_links",
                    models.TextField(blank=True, null=True, verbose_name="リンク切れ"),
                ),
                (
                    "crawled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="取得日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.category",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "記事",
                "verbose_name_plural": "記事",
                "db_table": "articles",
                "ordering": ["-post_date"],
                "managed": True,
            },
        ),
    ]
